apiVersion: v1
kind: Pod
metadata:
  name: downward
  labels:
    app: downward
spec:
  containers:
    - name: downward
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sleep", "9999999"]
      resources:
        requests:
          memory: 100Ki
          cpu: 15m
        limits:
          memory: 4Mi
          cpu: 100m
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CONTAINER_CPU_REQUEST_MILLICORES
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
              divisor: 1m
        - name: CONTAINER_MEMORY_REQUEST_KIBIBYTES
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Ki
  restartPolicy: Always
