apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap-mount-https
  labels:
    app: fortune
spec:
  containers:
    - name: fortune-configmap
      image: stiffme/fortune:env
      imagePullPolicy: IfNotPresent
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              key: sleep-interval
              name: fortune-https
      volumeMounts:
        - mountPath: /var/htdocs
          name: http
    - name: nginx
      image: nginx:alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: http
          readOnly: true
        - mountPath: /etc/nginx/conf.d/
          readOnly: true
          name: config
        - mountPath: /etc/nginx/certs
          readOnly: true
          name: certs
      ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
  volumes:
    - name: http
      emptyDir:
        medium: Memory
    - name: config
      configMap:
        name: fortune-https
        items:
          - key: my-nginx-config.conf
            path: https.conf
    - name: certs
      secret:
        secretName: fortune-https
  restartPolicy: Always
