apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap-mount
  labels:
    app: fortune
spec:
  containers:
    - name: fortuen-configmap
      image: stiffme/fortune:env
      imagePullPolicy: IfNotPresent
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              key: sleep-interval
              name: fortune-config
      volumeMounts:
        - mountPath: /var/htdocs
          name: http
    - name: nginx
      image: nginx:alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: http
          readOnly: true
        - mountPath: /etc/nginx/conf.d/
          readOnly: true
          name: config
      ports:
        - containerPort: 80
          name: http
  volumes:
    - name: http
      emptyDir:
        medium: Memory
    - name: config
      configMap:
        name: fortune-config
        items:
          - key: my-nginx-config.conf
            path: gzip.conf
  restartPolicy: Always
