apiVersion: v1
kind: Pod
metadata:
  name: fortune-env
  labels:
    app: fortune
spec:
  containers:
    - name: fortune-env
      image: stiffme/fortune:env
      imagePullPolicy: IfNotPresent
      env:
        - name: INTERVAL
          value: "5"
      volumeMounts:
        - mountPath: /var/htdocs
          name: http
    - name: nginx
      image: nginx:alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: http
          readOnly: true
      ports:
        - containerPort: 80
          name: http
  volumes:
    - name: http
      emptyDir:
        medium: Memory
  restartPolicy: Always
