apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  selector:
    app: kubia
  ports:
    - port: 80
      name: http
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubia
spec:
  selector:
    matchLabels:
      app: kubia
  serviceName: kubia
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia-pet
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /var/data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: microk8s-hostpath
        resources:
          requests:
            storage: 1Mi
        accessModes:
          - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: kubia-public
spec:
  selector:
    app: kubia
  ports:
    - port: 80
      targetPort: http
  type: ClusterIP
